### ISSUE TITLE
SocketCAN test

### ISSUE THREAD

**Issue by landonh12** [NXPHoverGames/zephyr#13]
Test SocketCAN sample at samples/net/socket/can

**Comment by sumitbatra-nxp** [comment]
Verified that SocketCAN is working between CAN0 and CAN1 transceivers

**Comment by sumitbatra-nxp** [comment]
Verified that SocketCAN is working between FMUK66 and NavQPlus

**Comment by sumitbatra-nxp** [comment]
2 SocketCAN interfaces can work in parallel with my changes in socketcan driver.
I tested it by switching CAN cable between 2 CAN slots on FMUK66 board on the fly.
Will check in he patch tomorrow.

**Comment by sumitbatra-nxp** [comment]
Following commit should serve the purpose -
https://github.com/zephyrproject-rtos/zephyr/commit/3be103b246f500c36a12487b33ef8a0e8a46c78c

**Comment by landonh12** [comment]
Looks to be completed.
