### ISSUE TITLE
SPI IMU support

### ISSUE THREAD

**Issue by landonh12** [NXPHoverGames/zephyr#8]
FXOS8700 and FXAS21002C SPI driver for Zephyr

**Comment by sumitbatra-nxp** [comment]
Added support for FXOS8700 over SPI in the newly created branch -
rddrone-fmuk66-imu
Commit ID: 6883f6a563e41fe9b9239b54f5933c68e08c4688

**Comment by sumitbatra-nxp** [comment]
Made following changes - 
1. Changes to manage chip Select of SPI1 for multiple slaves.
2. Reset SPI based slaves with RST pin and I2C slaves with CTRLREG1

FXAS21002 slave is working over SPI bus

**Comment by sumitbatra-nxp** [comment]
While enabling fxas21002 device tree changes were made which impacted fxos8700 as well, so verified that both fxos and fxas slaves are working with the current code.

**Comment by landonh12** [comment]
LGTM.
